// Common language
export const ARR_LANGUAGE = [
  { lang: "Tiếng Việt", code: "vi" },
  { lang: "English", code: "en" },
];

// List language code
export const DEFAULT_LANG = "vi";

// Namespace Key
export const NS_COMMON = "common";
export const NS_LOGIN = "login";

// Text Key
export const TXT_LOGIN = "TXT_LOGIN";
export const TXT_LOGOUT = "TXT_LOGOUT";
export const TXT_SHOP_LIST = "TXT_SHOP_LIST";
export const TXT_REGISTER_SHOP = "TXT_REGISTER_SHOP";
export const TXT_PROFILE = "TXT_PROFILE";
export const TXT_ID = "TXT_ID";
export const TXT_SHOP_NAME = "TXT_SHOP_NAME";
export const TXT_OWNER = "TXT_OWNER";
export const TXT_ADDRESS = "TXT_ADDRESS";
export const TXT_STAFF_NAME = "TXT_STAFF_NAME";
export const TXT_OWNER_NAME = "TXT_OWNER_NAME";
export const TXT_TELEPHONE = "TXT_TELEPHONE";
export const TXT_CONTRACT_PERIOD = "TXT_CONTRACT_PERIOD";
export const TXT_STATUS = "TXT_STATUS";
export const TXT_SETTING = "TXT_SETTING";
export const TXT_SEARCH = "TXT_SEARCH";
export const TXT_OWNER_INFORMATION = "TXT_OWNER_INFORMATION";
export const TXT_COMPANY_NAME = "TXT_COMPANY_NAME";
export const TXT_EMAIL = "TXT_EMAIL";
export const TXT_SALES_AGENCY = "TXT_SALES_AGENCY";
export const TXT_PASSWORD = "TXT_PASSWORD";
export const TXT_START_CONTRACT_PERIOD = "TXT_START_CONTRACT_PERIOD";
export const TXT_END_CONTRACT_PERIOD = "TXT_END_CONTRACT_PERIOD";
export const TXT_PORT_NUMBER = "TXT_PORT_NUMBER";
export const TXT_CITY = "TXT_CITY";
export const TXT_BUILDING = "TXT_BUILDING";
export const TXT_NOTIFICATION_EMAIL = "TXT_NOTIFICATION_EMAIL";
export const TXT_SHOP_INFORMATION = "TXT_SHOP_INFORMATION";
export const FN_PAGINATION = "FN_PAGINATION";
export const TXT_CONFIRMATION = "TXT_CONFIRMATION";
export const TXT_CONFIRM_PASSWORD = "TXT_CONFIRM_PASSWORD";
export const TXT_USER_NAME = "TXT_USER_NAME";
export const TXT_STATE = "TXT_STATE";
export const TXT_ROLE = "TXT_ROLE";
export const TXT_CREATED = "TXT_CREATED";
export const TXT_CHANGE_PASS = "TXT_CHANGE_PASS";
export const TXT_EDIT_PROFILE = "TXT_EDIT_PROFILE";
export const TXT_SAVE_PROFILE = "TXT_SAVE_PROFILE";
export const TXT_NAME_PRODUCT = "TXT_NAME_PRODUCT";
export const TXT_DESCRIPTION_PRODUCT = "TXT_DESCRIPTION_PRODUCT";
export const TXT_PRICE_PRODUCT = "TXT_PRICE_PRODUCT";
export const TXT_CATEGORY_PRODUCT = "TXT_CATEGORY_PRODUCT";
export const TXT_ID_PRODUCT = "TXT_ID_PRODUCT";
export const TXT_ADD_CATEGORY = "TXT_ADD_CATEGORY";
export const TXT_NEW_CATEGORY = "TXT_NEW_CATEGORY";
export const TXT_FROM = "TXT_FROM";
export const TXT_TO = "TXT_TO";
export const TXT_ADD_IMAGE = "TXT_ADD_IMAGE";
export const TXT_NAME_CATEGORY = "TXT_NAME_CATEGORY";
export const TXT_AMOUNT_ITEM = "TXT_AMOUNT_ITEM";
export const TXT_DESCRIPTION_CATEGORY = "TXT_DESCRIPTION_CATEGORY";
export const TXT_EDIT = "TXT_EDIT";
export const TXT_IMAGE = "TXT_IMAGE";
export const TXT_EDIT_CATEGORY = "TXT_EDIT_CATEGORY";
export const TXT_EDIT_PRODUCT = "TXT_EDIT_PRODUCT";
export const TXT_CANCER = "TXT_CANCER";
export const TXT_SAVE = "TXT_SAVE";
export const TXT_STATE_WORKING = "TXT_STATE_WORKING";
export const TXT_WORKING = "TXT_WORKING";
export const TXT_STOP_WORKING = "TXT_STOP_WORKING";
export const TXT_EXPIRED = "TXT_EXPIRED";
export const TXT_START = "TXT_START";
export const TXT_STOP = "TXT_STOP";
export const TXT_SORT_LANGUAGE = "TXT_SORT_LANGUAGE";
export const TXT_QR_CODE = "TXT_QR_CODE";
export const TXT_CONTRACT_INFO = "TXT_CONTRACT_INFO";
export const TXT_ORDER_HISTORY = "TXT_ORDER_HISTORY";
export const TXT_DOWNLOAD = "TXT_DOWNLOAD";
export const TXT_SMALL = "TXT_SMALL";
export const TXT_MIDDLE = "TXT_MIDDLE";
export const TXT_LARGE = "TXT_LARGE";
export const TXT_TYPE_SHOP = "TXT_TYPE_SHOP";
export const TXT_WIFI = "TXT_WIFI";
export const TXT_PASS_WIFI = "TXT_PASS_WIFI";
export const TXT_LINK_WEBSITE = "TXT_LINK_WEBSITE";
export const TXT_PAYMENTS = "TXT_PAYMENTS";
export const TXT_TIME_WORK = "TXT_TIME_WORK";
export const TXT_CHANGE_IMAGE = "TXT_CHANGE_IMAGE";
export const TXT_REMOVE = "TXT_REMOVE";
export const TXT_CONFIRM_REMOVE = "TXT_CONFIRM_REMOVE";
export const TXT_REMOVE_PRODUCT = "TXT_REMOVE_PRODUCT";
export const TXT_REMOVE_ITEM = "TXT_REMOVE_ITEM";
export const TXT_ADMIN = "TXT_ADMIN";
export const TXT_SHOP_ADMIN = "TXT_SHOP_ADMIN";
export const TXT_CREATE_SUCCESS = "TXT_CREATE_SUCCESS";
export const TXT_CREATE_FAILED = "TXT_CREATE_FAILED";
export const TXT_NEW_PASSWORD = "TXT_NEW_PASSWORD";
export const TXT_TABLE = "TXT_TABLE";
export const TXT_TIME_BOOKS = "TXT_TIME_BOOKS";
export const TXT_NAME_ITEM = "TXT_NAME_ITEM";
export const TXT_PENDING = "TXT_PENDING";
export const TXT_DOING = "TXT_DOING";
export const TXT_SUCCESS = "TXT_SUCCESS";
export const TXT_CANCEL = "TXT_CANCEL";

export const ARR_SHOP_LIST = [
  TXT_ID,
  TXT_SHOP_NAME,
  TXT_OWNER,
  TXT_ADDRESS,
  TXT_OWNER_NAME,
  TXT_TELEPHONE,
  TXT_CONTRACT_PERIOD,
  TXT_STATUS,
  TXT_SETTING,
];

export const ARR_HISTORY_BOOKING = [
  TXT_ID,
  TXT_TABLE,
  TXT_TIME_BOOKS,
  TXT_NAME_CATEGORY,
  TXT_NAME_ITEM,
  TXT_AMOUNT_ITEM,
  TXT_STATUS,
];

export const ARR_ADMIN_STATE = [TXT_WORKING, TXT_STOP_WORKING, TXT_EXPIRED];
export const ARR_ADMIN_OPTION = [TXT_EDIT, TXT_STOP, TXT_START];
export const ARR_ADMIN_WORKING = [TXT_WORKING, TXT_STOP_WORKING];
export const ARR_ADMIN_ROLE = [TXT_SHOP_ADMIN, TXT_ADMIN];
export const ARR_SHOP_STATE = [TXT_PENDING, TXT_DOING, TXT_SUCCESS, TXT_CANCEL];
