module.exports = [
  {
    lang_code: "vi",
    lang_name: "Tiếng Việt",
    name: "Tiếng Việt",
    order_list: 1,
  },
  {
    lang_code: "en",
    lang_name: "English",
    name: "Tiếng Anh",
    order_list: 2,
  },
  {
    lang_code: "zh-cn",
    lang_name: "简体中文",
    name: "Tiếng Trung giản thể",
    order_list: 3,
  },
  {
    lang_code: "zh-tw",
    lang_name: "中國傳統的",
    name: "Tiếng Trung truyền thống",
    order_list: 4,
  },
  {
    lang_code: "ru",
    lang_name: "русский",
    name: "Tiếng Nga",
    order_list: 5,
  },
  {
    lang_code: "ja",
    lang_name: "日本語",
    name: "Tiếng Nhật",
    order_list: 6,
  },
  {
    lang_code: "ko",
    lang_name: "한국어",
    name: "Tiếng Hàn",
    order_list: 7,
  },
  {
    lang_code: "fr",
    lang_name: "français",
    name: "Tiếng Pháp",
    order_list: 8,
  },
  {
    lang_code: "de",
    lang_name: "Deutsche",
    name: "Tiếng Đức",
    order_list: 9,
  },
  {
    lang_code: "ar",
    lang_name: "عربى",
    name: "Tiếng Ả Rập",
    order_list: 10,
  },
  {
    lang_code: "es",
    lang_name: "Español",
    name: "Tiếng Tây Ban Nha",
    order_list: 11,
  },
  {
    lang_code: "hi",
    lang_name: "हिंदी",
    name: "Tiếng Hindi",
    order_list: 12,
  },
  {
    lang_code: "pt",
    lang_name: "Português",
    name: "Tiếng Bồ Đào Nha",
    order_list: 13,
  },
  {
    lang_code: "bn",
    lang_name: "বাংলা",
    name: "Tiếng Bengali",
    order_list: 14,
  },
  {
    lang_code: "pa",
    lang_name: "ਪੰਜਾਬੀ ਦੇ",
    name: "Tiếng Punjabi",
    order_list: 15,
  },
  {
    lang_code: "jw",
    lang_name: "Jawa",
    name: "Tiếng Java",
    order_list: 16,
  },
  {
    lang_code: "ms",
    lang_name: "Malay",
    name: "Tiếng Mã Lai",
    order_list: 17,
  },
  {
    lang_code: "te",
    lang_name: "తెలుగు",
    name: "Tiếng Telugu",
    order_list: 18,
  },
  {
    lang_code: "mr",
    lang_name: "मराठी",
    name: "Tiếng Marathi",
    order_list: 19,
  },
  {
    lang_code: "ta",
    lang_name: "தமிழ்",
    name: "Tiếng Tamil",
    order_list: 20,
  },
  {
    lang_code: "my",
    lang_name: "မြန်မာဘာသာစကား",
    name: "Tiếng Myanmar",
    order_list: 21,
  },
  {
    lang_code: "lo",
    lang_name: "ລາວ",
    name: "Tiếng Lào",
    order_list: 22,
  },
  {
    lang_code: "id",
    lang_name: "bahasa Indonesia",
    name: "Tiếng Indo",
    order_list: 23,
  },
  {
    lang_code: "ca",
    lang_name: "català",
    name: "Tiếng Catalan",
    order_list: 24,
  },
  {
    lang_code: "cs",
    lang_name: "čeština",
    name: "Tiếng Séc",
    order_list: 25,
  },
  {
    lang_code: "hr",
    lang_name: "Hrvatski",
    name: "Tiếng Croatia",
    order_list: 26,
  },
  {
    lang_code: "el",
    lang_name: "Η ελληνική γλώσσα",
    name: "Tiếng Hy Lạp",
    order_list: 27,
  },
  {
    lang_code: "th",
    lang_name: "ไทย",
    name: "Tiếng Thái",
    order_list: 28,
  },
  {
    lang_code: "ur",
    lang_name: "اردو",
    name: "Tiếng Urdu",
    order_list: 29,
  },
];
